apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-order-deploy
  labels:
    name: microservice-order-deploy
    app: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-order
      type: microservice
  template:
    metadata: 
      name: microservice-order-pod
      labels:
        app: microservice-order
        type: microservice
    spec:
      containers:
        - name: microservice-order
          image: m0sh1n/orderapi:latest
          ports:
          - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              value: Server=mssql-service;Database=MoshinEcommerce;User=sa;Password=$VaxiDrez2025