apiVersion: v1
kind: Pod
metadata: 
  name: microservice-customer-pod
  labels:
    app: microservice-customer
    type: microservice
spec:
  container:
    - name: microservice-customer
      image: m0sh1n/customerapi:latest
      ports:
      - containerPort: 80
      env:
        - name: ConnectionStrings__DefaultConnection
          value: Server=mssql-service;Database=MoshinEcommerce;User=sa;Password=$VaxiDrez2025