apiVersion: v1
kind: Pod
metadata: 
  name: microservice-order-pod
  labels:
    app: microservice-order
    type: microservice
spec:
  container:
    - name: microservice-order
      image: m0sh1n/orderapi:latest
      ports:
      - containerPort: 80
      env:
        - name: ConnectionStrings__DefaultConnection
          value: Server=mssql-service;Database=MoshinEcommerce;User=sa;Password=$VaxiDrez2025